#!/bin/bash
#emacs: -*- mode: shell-script; c-basic-offset: 4; tab-width: 4; indent-tabs-mode: t -*- 
#ex: set sts=4 ts=4 sw=4 noet:
#-------------------------- =+- Shell script -+= --------------------------
#
# @file      run_tests.sh
# @date      Tue Aug  9 19:18:57 2011
# @brief
#
#
#  Yaroslav Halchenko                                            Dartmouth
#  web:     http://www.onerussian.com                              College
#  e-mail:  yoh@onerussian.com                              ICQ#: 60653192
#
# DESCRIPTION (NOTES):
#
#    Little helper script to check either tests/demos
#
# COPYRIGHT: Yaroslav Halchenko 2011
#
# LICENSE: MIT
#
#  Permission is hereby granted, free of charge, to any person obtaining a copy
#  of this software and associated documentation files (the "Software"), to deal
#  in the Software without restriction, including without limitation the rights
#  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#  copies of the Software, and to permit persons to whom the Software is
#  furnished to do so, subject to the following conditions:
#
#  The above copyright notice and this permission notice shall be included in
#  all copies or substantial portions of the Software.
#
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
#  THE SOFTWARE.
#
#-----------------\____________________________________/------------------

out=tests_output_`date +"20%y%m%d%H%M%S"`
timelimit=15
timeescape=$(($timelimit - 5))
timelimitkill=$(($timelimit + 5))

mkdir -p $out
{
	for f in "$@"; do
		echo -n "TEST $f: ";
		outlog="$out/${f%.*}.log"
		( sleep $timeescape; xdotool key Escape; ) &
		# if it is a function -- eval it, otherwise run the script
		if grep -v '^[% ]*$' AlphaAdditionTest.m| head -1 | grep -q -e '^ *function'; then
			timeout --kill-after=$timelimitkill $timelimit \
				octave -q --eval "${f%.m}" >| $outlog 2>&1
		else
			# just run it then
			timeout --kill-after=$timelimitkill $timelimit \
				octave -q $f >| $outlog 2>&1
		fi
		rv=$?
		# time to kill our xdotool
		kill %1 &>/dev/null || :
		if [ $rv = 124 ]; then st='TIMEOUT';
		elif [ $rv = 0 ]; then st='OK';
		else fout="`grep -v octave-core $outlog | tail -1`"; st="FAILED $fout"; fi
		echo $st
	done;
} | tee $out.log
